# This configuration file allows you to configure the back-end side of things
# The configuration file's location should be passed as the first argument when launching EpiLink manually

#################################################################################################
# TAKE THE TIME TO GO THROUGH THIS CONFIGURATION FILE ENTIRELY! It contains a lot of useful     #
# information that will make your life much easier. It also includes security information which #
# which you should really be careful about.                                                     #
#################################################################################################

# Misconfigurations are always reported in the logs as WARN or ERROR.
# This configuration sample contains a *lot* of comments. You can remove all of them to get a much cleaner and compact file.

# Also check out the Maintainer's Guide for more information on everything!
#    --> --> https://epilink.zoroark.guru/#/MaintainerGuide <-- <--

# The name of the server. You can customize this if you want to.
name: My EpiLink Instance

# HTTP server configuration
server:
  # The port that should be used for the server.
  port: 9090

  # Either None, Forwarded or XForwarded depending on how you use your reverse proxy to transmit the remote host's
  # information
  # !!SWITCH TO THE CORRECT VALUE! FAILURE TO DO SO COULD LEAD TO SECURITY FLAWS!!
  # !!Make sure your reverse proxy overrides values the client sends. See here for more info: !!
  # --> --> https://docs.zoroark.guru/#/ktor-rate-limit/usage?id=reverse-proxies-and-ip-address-spoofing <-- <--
  # - None: No reverse proxy used, use the host's information directly
  # - XForwarded: Use the X-Forwarded-* headers to get information about the remote host
  # - Forwarded: Use the Forwarded standard header to get information about the remote host
  proxyType: None

  # The URL of the front-end, WITH a trailing slash /, or null if the URL is unknown
  frontendUrl: null

  # (Optional) Custom logo that will be displayed to the user. ~ means default, in which case it will show EpiLink's
  # logo.
  logo: ~
  # To use a logo from a URL, use this syntax
  #logo: { url: "https://..." }
  # To use a logo stored next to this configuration file, use this syntax
  #logo: { file: mylogo.jpg }
  # or, if you want to also specify the contentType (recommended for SVG files)
  #logo: { file: mylogo.svg, contentType: image/svg+xml }

  # (Optional) Custom background that will be displayed to the user on the website. ~ means default, in which case a
  # simple grey background is shown. Same syntax as for the logo
  background: { file: bg.jpg }
  
  # An optional list of custom footers that should be shown on the front-end
  footers: # optional
    - name: My Footer URL
      url: "https://example.com"

  # True to enable /api/v1/admin endpoints, false to disable them. Optional, true by default.
  #enableAdminEndpoints: true

  # Cooldown between an identity-sensitive event (e.g. ban, adding the identity, identity access) and users being able
  # to remove their identity in seconds. Optional, 3600 seconds (1 hour) by default
  #unlinkCooldown: 3600

  # Rate limiting profile. This can be changed if you expect big loads on your server from a single IP address
  # Check the maintainer guide for guidance on which profile to choose. Harsh profile by default.
  #rateLimitingProfile: Harsh

# Name and location of the EpiLink SQLite database
db: data/epilink.db

# Redis URI to the Redis instance to use
# Format: https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details#uri-syntax
# Currently bound to the Redis created by the docker-compose file
redis: "redis://redis:6379"

# List of administrators (Discord IDs of the administrator)
# For example admins: [12354, 987234, 12341]
# /!\ Administrators have a lot of power over the application, be careful with who you trust!
admins: []

# Identity Provider configuration
idProvider:

  # Issuer/Authority URL for the OpenID provider
  url: ...

  # Name of the OpenID provider, used in the front-end (Sign in with ...)
  name: ...

  # Icon for the OpenID provider, used in the front-end (Logo for Sign in button)
  # Same format as for the background and logo from the server config (see above)
  icon: { url: ... }


# The tokens to use when connecting
# Note that providing them in the configuration file is optional. If you do not define them here, you can pass them as
# environment values.
tokens:
  # The token for the Discord bot
  discordToken: ...
  # The client ID for Discord's OAuth2
  discordOAuthClientId: ...
  # The secret for Discord's OAuth2
  discordOAuthSecret: ...
  # The client ID for the ID Provider's OAuth2
  idpOAuthClientId: ...
  # The secret for the ID Provider's OAuth2
  idpOAuthSecret: ...

# Rulebook declaration
# See the docs for more information
#----#
#rulebook: |
#  "MyRule" { ... }
# OR #
#rulebookFile: myFile.rule.kts

# EpiLink has to compile rulebooks in order to use them. If set to true, the compiled rulebook gets saved and is loaded
# instead of the real one if nothing was changed in order to save time when starting EpiLink. If set to false, the
# rulebook is compiled every time. True by default.
# cacheRulebook: true

# Terms of services, etc. See the maintainer guide for more details.
#legal:
  # Terms of services
  # tos: |
  #     <p> My terms of services...</p>
  # OR
  # tosFile: myTermsOfServices.html

  # Privacy policy
  # policy: |
  #     <p>My privacy policy...</p>
  # OR
  # policyFile: myPrivacyPolicy.html

  # ID Prompt text disclaimer
  # identityPromptText: <p>My text...</p>

# You can also add a "privacy:" section to enable/disable some notifications. See the maintainer guide for more details.

# Configuration for everything related to handling Discord servers
# When something is optional, you can omit it entirely.
# When something is nullable, you can replace its value by ~ to indicate that the value is unknown.
discord:
  # The URL displayed as the log-in URL in the bot's default welcome messages (nullable)
  welcomeUrl: "https://my.amazing.welcome.page/hello"

  # The prefix to use for commands. e! by default.
  #commandsPrefix: "e!"

  # The default language that will be used if users did not define a role for themselves
  #defaultLanguage: en

  # The list of preferred languages that will be shown before all others in EpiLink's language-related messages. Must
  # include the default language.
  #preferredLanguages: [en]

  # List of EpiLink roles that the bot can add but will NOT remove (they "stick" to users), even if it is determined
  # that they should not be there. This one applies to all servers, you can also use this option on individual servers.
  # Optional, empty list by default.
  #stickyRoles: []

  # The list of servers where EpiLink should do its magic. Note that you must add the bot to these servers in order
  # for all of this to work (an invite link is sent in the logs when starting EpiLink so you can add the bot to your
  # servers)
  servers:
    - # Each server gets one entry here.
      # The Discord ID of the server
      id: 123456789
      # Roles dictionary. The role on the left denotes the EpiLink role (either internal or custom)
      # and the value on the right indicates the Discord role ID to attribute to those who match the EpiLink role
      # Check the maintainer guide for information on the roles.
      roles:
        _known: 1239121323
        _identified: 195923842

      # Required rules for this server. These are the names of the rules that should be launched when trying to
      # determine roles for a user. You can omit it if you do not use rules or custom roles for this server.
      #requires: [ "a rule", "another rule" ]

      # True if the server should send a message to unknown users who join the server, false otherwise.
      # (optional, true by default)
      enableWelcomeMessage: true
      # Same as the stickyRoles in discord:, but applies only to this server. Optional, empty list by default.
      #stickyRoles: []
      # The embed to be displayed when the user first joins. If null, displays a default message.
      # (nullable, optional with null by default). You can remove this entire section if you don't need a custom embed.
      #welcomeEmbed:

        # ALL of the fields of an embed here are nullable and optional (null by default) unless otherwise noted
        # i.e. you can omit any of them if you don't need them

        #The title of the embed
        #title: Welcome to my great server!

        # The description (main content) of the embed
        #description: |
        #  This is an example embed, because I forgot to change the configuration file. Woops!
        #
        #  In the mean time, remember that life begins with an L and ends with an E. Yeah, I don't know what that is supposed to mean either.

        # The URL that is accessed when clicking on the embed's title
        #url: "https://hello/world"

        # A color, either with its name (only supports a few simple color names) or its hexadecimal code with a leading number sign: #ab12ef
        #color: "#12eb99"

        # The footer of the embed (small field at the bottom)
        #footer:
          # The text displayed in the footer (mandatory if the footer is declared)
          #text: This is my footer
          # The URL to an icon that is displayed in the footer
          #iconUrl: "https://my/amazing/image.png"

        # URL to the image to display in the embed
        #image: "https://my/great/stuff.png"

        # URL to the thumbnail image of the embed
        #thumbnail: "https://my/great/thumbnail.png"

        # Author information (displayed at the very top of the embed)
        #author:
          # The name of the author (mandatory if the author is declared)
          #name: My amazing bot
          # The URL to go to when clicking on the author's name
          #url: "https://my.bot.website/yes"
          # The URL for the author's icon
          #iconUrl: "https://amazing.url/image.png"

        # A list of the fields of the embed
        #fields:
          # One item per field. Name is the field's title and value is the field's content.
          # Both are mandatory for each field.
          #- name: My field
            #value: |
            #  This is the content of my field. How extraordinary.
            #
            #  YEET
            #---- Inline fields (true) will be displayed side by side, non-inline fields (false) will be displayed with one
            #---- on each entire line. Optional, default is true.
            #inline: true
